class ETLConfig:
    CSV_DATA_PATH = '../csv_data/SHIB-USD.csv'
    MYSQL_HOST = 'localhost'
    MYSQL_USER = 'root'
    MYSQL_PASSWORD = 'root'
    MYSQL_DB = 'stocks'
    JSON_DATA_PATH = '../json_data/'
    MSSQL_SERVER = 'mssql_server'
    MSSQL_DATABASE = 'mssql_database'
    MSSQL_USERNAME = 'mssql_username'
    MSSQL_PASSWORD = 'mssql_password'