class ETLConfig:
    CSV_DATA_PATH = '../csv_data/'
    MYSQL_HOST = 'localhost'
    MYSQL_USER = 'root'
    MYSQL_PASSWORD = 'root'
    MYSQL_DB = 'stocks'
    JSON_DATA_PATH = '../json_data/'
    MSSQL_SERVER = 'CRIBL-MOIZAABD1'
    MSSQL_DATABASE = 'bookstore'
    MSSQL_USERNAME = 'root'
    MSSQL_PASSWORD = 'root'
